export const backendData = {
  code: 0,
  result: {
    standardAdList: [],
    liteAdList: [
      {
        _id: "65fb96e46d09b7001d9d1fa0",
        gymName: "시청 무브짐앤무브맥스PT",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e5ec56c2a2c8a2e4/2WMqrmKY6Sakmdrwo7uXrELngTjjummNA7rG.Big_240324_무브짐앤무브맥스PT시청점_13.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e5ec56c2a2c8a2e4/2YUds6u8BgAsm4SVkFLcbpLqT6Y1au448n6K.Small_240324_무브짐앤무브맥스PT시청점_13.jpg",
        address: "서울 중구 서소문동",
        location: [126.97363348811612, 37.563331828432155],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "샤워실 / 수건 / 대형제빙기 / ️ 무료주차 2시간 30분 / 인바디 측정",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 450000,
          originalPrice: 528000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 10,
        },
        review: {
          rate: 5,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "59e4360761a74379ba5738ac",
        gymName: "서대문역 VIP 휘트니스",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15f23730f0d4746062/4K6CpJYkn2FxX8CjH1MrrvAGtZsr251Gk9JabUig3AHm.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15f23730f0d4746062/4K6CpJYkn2FxX8CjH1MrrvAGtZsr251Gk9JabUig3AHn.jpg",
        address: "서울 서대문구 충정로2가",
        location: [126.964323, 37.564755],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "‍ O.T (3개월 이상 등록시 - 30분 1회 )",
        },
        service: {
          free: "운동복 / 수건 / 샤워실 / 인바디 / 주차는 리프트안 승용차만 2시간가능",
        },
        price: {
          name: "헬스+운동복",
          count: null,
          isLowestPrice: false,
          lowestPrice: 462000,
          originalPrice: 462000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.94,
          count: 13,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
    ],
    centerList: [
      {
        _id: "660a38ad5e60cd001dff059b",
        gymName: "기장 헬스달리아",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e97ed662cdb03ca/2fGtTg5He46WWZZEUhjqH6JpdRe8Zx62g11j.list_photo.jpg",
        address: "부산 기장군 기장읍 동부리",
        location: [129.2180885119647, 35.249368193028],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복+수건 / ️주차",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 292000,
          originalPrice: 292000,
          period: 6,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6110ec11ec7d1e0039f4da2a",
        gymName: "가락시장 헬스보이짐 프리미엄",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17b2a1a2433315c06a/4K7xc6tKNrThd4qH1dFTdsdhVuP3K5a1SkXEspEX6pJt.jpg",
        address: "서울 송파구 가락동",
        location: [127.11885802661516, 37.49311553608278],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "O.T (3회 트레이너 선생님과 스케줄 조율 필요)",
        },
        service: {
          free: "Wi-fi / 수건 / 샤워시설",
        },
        price: {
          name: "헬스",
          count: null,
          isLowestPrice: false,
          lowestPrice: 840000,
          originalPrice: 840000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.13,
          count: 16,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "64d9e7776f0347001d175b39",
        gymName: "해운대 아시아짐 헬스&PT",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/189f3302a684dda291/2WjAVsUT27U6TUMaa294qJTMoMov4MDeuHjr.센터 Small 복사.jpg",
        address: "부산 해운대구 우동",
        location: [129.1616436, 35.1637804],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / 주차 (2,000cc 이상 불가)",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 285000,
          originalPrice: 300000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 9,
        },
        review: {
          rate: 5,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5b888f05ac760139ba53e88d",
        gymName: "능평 Y GYM 헬스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1658d6eace138fc55e/Small)Ygym.jpg",
        address: "경기 광주시 오포읍 능평리",
        location: [127.176203, 37.345873],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 550000,
          originalPrice: 550000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "635a1d52f2c292001dd9df0d",
        gymName: "화곡 헬스와 필라테스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/184180288d03627a24/48Yvy6Rn82EeD1yphhwDaXbiZ4g1VRXBDh7g.list_photo.jpg",
        address: "서울 강서구 화곡동",
        location: [126.84366985332811, 37.543738201341434],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "필라테스 가입자에 한해 필라테스룸 무료 이용",
        },
        service: {
          free: "주차 2시간 30분 가능 / 6개월권 부터는 운동복 무료 / 가입기간 관계없이 수건 무료 이용",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 359000,
          originalPrice: 359000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.94,
          count: 16,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6113abb7ec7d1e0039f525ab",
        gymName: "인계 헬스보이짐 프리미엄",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17b34d6c65e58d775b/4K7xc94JmSsze43NdJyGmiWDJvaCeDD22yvTcb7ikNrU.jpg",
        address: "경기 수원시 팔달구 인계동",
        location: [127.032134, 37.263638],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "기구필라테스", "크로스핏", "골프"],
        program: {
          free: "O.T (3회 , 담당트레이너와 스케줄 조율)",
        },
        service: {
          free: "주차비 3시간30분 무료/ 수건 / 안마의자 / 샤워시설 / WI-FI",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 720000,
          originalPrice: 720000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.74,
          count: 19,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6351086172c39f001d7efb8d",
        gymName: "송천 헬스보이짐&사우나",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/183f488bbd95ac4253/4K8gXNobxZGm3DDsWgZcj8FiHvCHox7qFeVKutkbmyWY.jpg",
        address: "전북 전주시 덕진구 송천동1가",
        location: [127.11892404058153, 35.85297604300977],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "‍ 매월 O.T 3회",
        },
        service: {
          free: "샤워실 / 수건 / ️ 주차시간제한 없음 / 인바디",
        },
        price: {
          name: "헬스+사우나",
          count: null,
          isLowestPrice: true,
          lowestPrice: 423000,
          originalPrice: 468000,
          period: 6,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 3,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "61a726079ffe870078d607ec",
        gymName: "동탄 헬스더맥스 24시",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17d74ec8e1b2aeff27/4K7y1ZhXyNKFmBzEyWyR6ejzLKTBoV61tWGBEXXCFrp8.jpg",
        address: "경기 화성시 반송동",
        location: [127.073736, 37.207372],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "요가", "G.X"],
        program: {
          free: "-S.P.T(서비스 피티) 신규 등록하신 회원님의 목적에 맞는 1:1트레이닝 제공 / ※ 트레이너와 스케줄 조율 필요합니다. / / -U.D.T(우리동네트레이너)서비스 / ※UDT완장을 차고 있는 트레이너에게 언제든지 운동에 필요한 궁금증을 해소할 수 있는 서비스입니다.",
        },
        service: {
          free: "주차 4시간 무료 / 공용락커 / 샤워장 (샴푸, 컨디셔너, 바디워시 무료) / Wi-Fi",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 756000,
          originalPrice: 840000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 7,
        },
        review: {
          rate: 5,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "62ba8b39bfc71e001d258013",
        gymName: "매탄 헬스보이짐 프리미엄",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/181a8afd90a1c25f51/4K8g7ua9NeYNwR7sDqZcB5eLP6Bu4TBnic5D9vuAoZdA.jpg",
        address: "경기 수원시 영통구 매탄동",
        location: [127.04538100956671, 37.25801102074371],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "사우나"],
        program: {
          free: "",
        },
        service: {
          free: "주차 3시간 무료",
        },
        price: {
          name: "헬스  회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 599000,
          originalPrice: 680000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 4,
        },
        review: {
          rate: 4.94,
          count: 51,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "61273e726bdf9700390823b6",
        gymName: "송촌 헬스보이짐 프리미엄",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17b814bef682b5a378/4K7xcNBz1n7XK7BfQaoUxo2iKDUM7aUkRuN7Rwbtx46U.jpg",
        address: "대전 대덕구 송촌동",
        location: [127.43820869233137, 36.36699899557096],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "기구필라테스", "사우나", "P.T"],
        program: {
          free: "O.T (월 3회 30분) / 필라 O.T",
        },
        service: {
          free: "수건 / Wi-fi",
        },
        price: {
          name: "헬스+사우나",
          count: null,
          isLowestPrice: false,
          lowestPrice: 800000,
          originalPrice: 800000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스", "사우나"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 2.46,
          count: 7,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "652e4aef8d5c02001d3e8911",
        gymName: "신도림 리커버 헬스&필라테스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18b3cd4b7495cf8646/2YWejgxHsiYcgHL5eRHwZxy7THfUR3bKv7Ai.list_photo.jpg",
        address: "서울 구로구 구로동",
        location: [126.89145443546595, 37.505400101210675],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "필라테스", "P.T"],
        program: {
          free: "6:1 원데이 클래스 / 개인 맞춤형 1:1 레슨",
        },
        service: {
          free: "운동복+수건 / 주차 3시간 / 샴푸+바디워시",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 429000,
          originalPrice: 540000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 6,
        },
        review: {
          rate: 4.89,
          count: 9,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6295e2674600ae001d2ecc33",
        gymName: "고터 헬스보이짐 프리미엄",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/181197c65495ab1279/43VzvqwVEfK9MkRhXWuWpwABLaW766rNZ9VC.list_photo.jpg",
        address: "서울 서초구 반포동",
        location: [127.0068537765553, 37.50596785112526],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 850000,
          originalPrice: 850000,
          period: 12,
          priceType: "period",
          itemTags: [],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.33,
          count: 3,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "62f631764d657b001d9f831c",
        gymName: "가산 헬스보이짐&골프인",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18291b136d6168f1bf/4K8gHiEXipv4AaiArZu1XR7CPa2zYcB5MWAiicF4TGNL.jpg",
        address: "서울 금천구 가산동",
        location: [126.884507668482, 37.4795278609345],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "골프"],
        program: {
          free: "",
        },
        service: {
          free: "주차 2시간 가능",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 595000,
          originalPrice: 605000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 7,
        },
        review: {
          rate: 5,
          count: 10,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6538cfbf223a711111902584",
        gymName: "평촌 헬스코인",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18b65eb827b38e2eea/A8q5kBYqCV7hNi4zPQHFyRxtJS4oj2nrp.센터 Small 복사.jpg",
        address: "경기 안양시 동안구 평촌동",
        location: [126.97565281452925, 37.39226659902655],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 양말 / 호텔식샤워수건 / 주차",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 480000,
          originalPrice: 480000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5b6c6c20729a8461514bea7c",
        gymName: "애오개 헬스존",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1651f865fbf5da8d11/2Y9Kv1ReEdgY83knduJVLifwzAd1L1RwysoY.Small_231212_애오개_헬스존_07.jpg",
        address: "서울 마포구 공덕동",
        location: [126.960333, 37.550072],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 3시간 / ️수건 + 탈의실 락커",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 400000,
          originalPrice: 400000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.83,
          count: 18,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6478433bf3cbba001d5f4f55",
        gymName: "부평 노력의천재 헬스&PT",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18875c6a0c120fe43/kXkA9EVriGUYZArwZQn5eXDnp9mPDznf4Rbs3HXMkt.jpg",
        address: "인천 부평구 갈산동",
        location: [126.72356183533834, 37.515925019863396],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️수건",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 400000,
          originalPrice: 400000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "60b5f087c70b9e0039955cfe",
        gymName: "삼성 헬스인",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/179c6b391652d75c5d/2YATpsyw1fj7q7PWCV1Y6fSZ3WC7V59SNSg3.Small_240123_삼성_헬스인_03.jpg",
        address: "서울 강남구 삼성동",
        location: [127.05269862435, 37.5134546142336],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️수건 / Wi-fi / 주차",
        },
        price: {
          name: "헬스 회원권",
          count: 40,
          isLowestPrice: false,
          lowestPrice: 199000,
          originalPrice: 199000,
          period: null,
          priceType: "count",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6113c9abec7d1e0039f52b74",
        gymName: "영등포 헬스보이짐&필라걸",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17b354bc5f61195e6d/4K7xc94nuJRpdouLLyEUYvgoMWv6Y88KhAcHGZmUFG1v.jpg",
        address: "서울 영등포구 문래동3가",
        location: [126.898573, 37.514557],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "기구필라테스", "P.T"],
        program: {
          free: "WPT(Welcome Personal Training) 3회 개인레슨 프로그램 / ※담당 강사 및 트레이너와 스케줄 조율 / / 기구필라테스 이용 고객님께 헬스 이용권 증정",
        },
        service: {
          free: "샤워실 / 수건 / ️ 주차 2시간 가능 / 인바디 / ‍ 안마의자",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 620000,
          originalPrice: 620000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 19,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "652747818d5c02001d3b2eaf",
        gymName: "불광 헬스보이짐&필라걸",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18b216f51113bbf590/2YUxaCHxdtPU3R4ASwu1Ms8rKQUh4j4UzHGP.센터 Small 복사.jpg",
        address: "서울 은평구 불광동",
        location: [126.92932091666563, 37.61179602592527],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "필라테스"],
        program: {
          free: "WPT",
        },
        service: {
          free: "운동복+수건 / 주차 2시간",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 480000,
          originalPrice: 480000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 13,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "630c1e8ffcfee846835b402d",
        gymName: "복대 헬스보이짐&필라걸",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/182e7576005210d077/4K8gKi9VL6o25g2DvBx91dbifkAZeNtoJ77jKrvRVJxQ.jpg",
        address: "충북 청주시 흥덕구 복대동",
        location: [127.4268496191905, 36.64217102638187],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "기구필라테스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "샤워실 / 수건 / ️ 주차 2시간 가능",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 590000,
          originalPrice: 601400,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 9,
        },
        review: {
          rate: 4.67,
          count: 3,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
    ],
  },
};
