export const backendData = {
  pageProps: {
    user: {
      id: 0,
      nickName: null,
      sex: null,
      profileImage: null,
      level: 0,
      birthYear: 0,
      country: null,
    },
    authorization: "3eae85842b644f6883c5c42238ebd9e2",
    query: {
      category: "코성형",
      country: "kr",
    },
    language: "ko-KR",
    title: "이벤트 | 강남언니 - 1등 성형수술&피부시술 정보앱 | 코성형",
    data: {
      events: {
        reason: "SUCCESS",
        data: [
          {
            id: 48314,
            titleImage:
              "https://image2.gnsister.com/images/direct/1679981383061_4f05e4fcccba45ecab3e2dfd47335cb7.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "제스타 코성형",
            hospitalId: 352,
            hospitalName: "제스타성형외과",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 170,
            discountedCost: 1870000,
            cost: 1870000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1679954474000,
          },
          {
            id: 36650,
            titleImage:
              "https://image2.gnsister.com/images/direct/1708658222361_d7cc06f9118d48479697f6135b7f8b3b.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "디엔드 첫 코성형",
            hospitalId: 419,
            hospitalName: "디엔드성형외과",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "서초구",
            rating: 10,
            ratingCount: 103,
            discountedCost: 1400000,
            cost: 1400000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1660697156000,
          },
          {
            id: 22013,
            titleImage:
              "https://image2.gnsister.com/images/direct/1683611313931_ba1b4e1901024165b2d8b7a946dc978e.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "올라인 코성형",
            hospitalId: 3391,
            hospitalName: "라스트성형외과",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 186,
            discountedCost: 1639000,
            cost: 1639000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1626972465000,
          },
          {
            id: 37233,
            titleImage:
              "https://image2.gnsister.com/images/direct/1713404426366_26657fc695f547699e336048da66ff78.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "어반 자려한 코성형 ",
            hospitalId: 4256,
            hospitalName: "어반성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 142,
            discountedCost: 1639000,
            cost: 1639000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1661884406000,
          },
          {
            id: 19439,
            titleImage:
              "https://image2.gnsister.com/images/direct/1701664551138_a6d2c7d6fcaa44928ea2350ef4d09577.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "첫단추, 김태환 코재수술",
            hospitalId: 3239,
            hospitalName: "첫단추의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "서초구",
            rating: 10,
            ratingCount: 64,
            discountedCost: 3180000,
            cost: 3180000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1619549023000,
          },
          {
            id: 64303,
            titleImage:
              "https://image2.gnsister.com/images/direct/1709521692540_24261890d6994d288fda8f2983dfcecd.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "인트로 첫코성형",
            hospitalId: 5280,
            hospitalName: "인트로성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "서초구",
            rating: 10,
            ratingCount: 41,
            discountedCost: 1649000,
            cost: 1649000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1701105810000,
          },
          {
            id: 15883,
            titleImage:
              "https://image2.gnsister.com/images/direct/1687496978354_cf74ba1a47ea4cb1a82c88993b3b2c7a.png?originalImageWidth=1080&originalImageHeight=1080",
            title: "딱 맞는 입체코성형",
            hospitalId: 1389,
            hospitalName: "잇츠비의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "서초구",
            rating: 10,
            ratingCount: 42,
            discountedCost: 1980000,
            cost: 3900000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1607371616000,
          },
          {
            id: 81341,
            titleImage:
              "https://image2.gnsister.com/images/direct/1715059691077_0c2b1294b3fc421589d37bd3a66fcb7c.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: " 추가비용 절대 없는 무조건 이 가격 기증늑연골 코재수술",
            hospitalId: 288,
            hospitalName: "안성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 12,
            discountedCost: 3289000,
            cost: 5170000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1715034726000,
          },
          {
            id: 51072,
            titleImage:
              "https://image2.gnsister.com/images/direct/1685939800391_d00e84bfe0d348c7ac96a1687314f7e9.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "성품_첫코성형",
            hospitalId: 5002,
            hospitalName: "성품성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "서초구",
            rating: 10,
            ratingCount: 9,
            discountedCost: 1650000,
            cost: 1650000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1685910372000,
          },
          {
            id: 74620,
            titleImage:
              "https://image2.gnsister.com/images/direct/1707115237873_2ebf4a0ea04340e5b17c802690b22d65.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "어반 기능코성형",
            hospitalId: 4256,
            hospitalName: "어반성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 31,
            discountedCost: 550000,
            cost: 550000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1707169271000,
          },
          {
            id: 73427,
            titleImage:
              "https://image2.gnsister.com/images/direct/1709199949321_d3d1cf4fa5c14b17b349a8167b9ef304.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "1석2조 코끝성형&돌출입교정",
            hospitalId: 4277,
            hospitalName: "이에스청담성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 15,
            discountedCost: 770000,
            cost: 770000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1705870294000,
          },
          {
            id: 75709,
            titleImage:
              "https://image2.gnsister.com/images/direct/1715925739925_846cc13c4ddd4812a5ae82fa4ddab5a8.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "현대미학 코성형 특가",
            hospitalId: 207,
            hospitalName: "현대미학성형외과",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 16,
            discountedCost: 710000,
            cost: 710000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1708896969000,
          },
          {
            id: 64497,
            titleImage:
              "https://image2.gnsister.com/images/direct/1701229605117_648462a40f8c417fa5926508c2a724e0.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "그랜드 코재수술, 마지막 코수술도 GRAND",
            hospitalId: 62,
            hospitalName: "그랜드성형외과",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 13,
            discountedCost: 2750000,
            cost: 4400000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1701205158000,
          },
          {
            id: 60473,
            titleImage:
              "https://image2.gnsister.com/images/direct/1711331727985_8b4988a34fc4499ca416f11f92caf1a0.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "워나 _ 코재수술",
            hospitalId: 5448,
            hospitalName: "워나성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "서초구",
            rating: 10,
            ratingCount: 14,
            discountedCost: 2189000,
            cost: 3500000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1698265585000,
          },
          {
            id: 56330,
            titleImage:
              "https://image2.gnsister.com/images/direct/1694152261224_c5d7819b5b0a4500a9909fe93bdfde21.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "에이탑 트리플라인 인중코성형",
            hospitalId: 300,
            hospitalName: "에이탑성형외과",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 28,
            discountedCost: 2255000,
            cost: 2255000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "GROWTH",
            createTime: 1692555292000,
          },
          {
            id: 57218,
            titleImage:
              "https://image2.gnsister.com/images/direct/1716946529062_cfe0b3a0bc9145978acc89901a44390e.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "다비다 퓨어 첫코성형",
            hospitalId: 5257,
            hospitalName: "다비다성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 25,
            discountedCost: 990000,
            cost: 990000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1694044413000,
          },
          {
            id: 78734,
            titleImage:
              "https://image2.gnsister.com/images/direct/1710990468040_4e4708b26877427f96e1856afc25975c.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "어반 _ 남자 코 성형",
            hospitalId: 4256,
            hospitalName: "어반성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 9,
            discountedCost: 715000,
            cost: 715000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1710978790000,
          },
          {
            id: 12581,
            titleImage:
              "https://image2.gnsister.com/images/direct/1692336607640_d01b49373f5a426585521256df72dd3a.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "리앤리 맞춤 코성형",
            hospitalId: 2159,
            hospitalName: "리앤리성형외과",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 7,
            discountedCost: 979000,
            cost: 979000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1589305810000,
          },
          {
            id: 22664,
            titleImage:
              "https://image2.gnsister.com/images/direct/1686125275850_d43abc4c695943b6ae4a098775ecddf2.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "더비비 첫 코성형",
            hospitalId: 3423,
            hospitalName: "더비비성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "강남구",
            rating: 10,
            ratingCount: 8,
            discountedCost: 1639000,
            cost: 1639000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1630013971000,
          },
          {
            id: 76441,
            titleImage:
              "https://image2.gnsister.com/images/direct/1717058748686_c72ca6a1c3ae43f38bab0d87aaa0e7f4.jpg?originalImageWidth=1080&originalImageHeight=1080",
            title: "남자 첫코성형",
            hospitalId: 5448,
            hospitalName: "워나성형외과의원",
            hospitalSubway: null,
            hospitalSido: "서울",
            hospitalCountry: "KR",
            hospitalSiGunGu: "서초구",
            rating: 10,
            ratingCount: 5,
            discountedCost: 1539000,
            cost: 3000000,
            currency: "KRW",
            showVatBadge: true,
            useBuyNow: false,
            assessmentState: "CERTIFIED",
            createTime: 1709675527000,
          },
        ],
        start: 0,
        length: 20,
        recordsTotal: 661,
        recordsFiltered: 661,
      },
      categories: [
        {
          id: 413,
          name: "눈성형",
          normalIconUrl: "https://image2.gnsister.com/images/icon/eye_off.png",
          selectedIconUrl: "https://image2.gnsister.com/images/icon/eye_on.png",
        },
        {
          id: 412,
          name: "코성형",
          normalIconUrl: "https://image2.gnsister.com/images/icon/nose_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/nose_on.png",
        },
        {
          id: 414,
          name: "안면윤곽/양악",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/faceline_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/faceline_on.png",
        },
        {
          id: 421,
          name: "가슴성형",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/breast_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/breast_on.png",
        },
        {
          id: 422,
          name: "지방성형",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/bodyline_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/bodyline_on.png",
        },
        {
          id: 416,
          name: "필러",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/filler_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/filler_on.png",
        },
        {
          id: 415,
          name: "보톡스",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/botox_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/botox_on.png",
        },
        {
          id: 419,
          name: "리프팅",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/transplant_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/transplant_on.png",
        },
        {
          id: 411,
          name: "피부",
          normalIconUrl: "https://image2.gnsister.com/images/icon/acne_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/acne_on.png",
        },
        {
          id: 537,
          name: "제모",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/waxing_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/waxing_on.png",
        },
        {
          id: 418,
          name: "모발이식",
          normalIconUrl: "https://image2.gnsister.com/images/icon/hair_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/hair_on.png",
        },
        {
          id: 420,
          name: "치아",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/teethandoptical_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/teethandoptical_on.png",
        },
        {
          id: 417,
          name: "한방",
          normalIconUrl:
            "https://image2.gnsister.com/images/icon/oriental_off.png",
          selectedIconUrl:
            "https://image2.gnsister.com/images/icon/oriental_on.png",
        },
        {
          id: 423,
          name: "기타",
          normalIconUrl: "https://image2.gnsister.com/images/icon/etc_off.png",
          selectedIconUrl: "https://image2.gnsister.com/images/icon/etc_on.png",
        },
      ],
      defaultText: {
        discountedCost: "특가",
      },
    },
    cookies: {
      token: "3eae85842b644f6883c5c42238ebd9e2",
      _fbp: "fb.1.1716946656898.521095377",
      _gcl_au: "1.1.1799406335.1716946657",
      _tt_enable_cookie: "1",
      _ttp: "nbTDEUjdg3jn9UW0eMUCDFBVEgg",
      ab180ClientId: "3b1d2948-1481-415a-94e5-257d4a5ebc4e",
      _gid: "GA1.2.509920185.1717124522",
      _ga_GXB8082VP1: "GS1.1.1717124522.2.1.1717124681.60.0.0",
      _ga: "GA1.1.1277724972.1716946657",
      airbridge_session:
        '{"id":"c163a491-cb5c-433d-a6d8-8bbb94682286","timeout":1800000,"start":1717124523411,"end":1717124682147}',
      _dd_s: "rum=0&expire=1717125822057",
      "amplitude_id_ee9e97f46fa77da052305bb94e327b88gangnamunni.com":
        "eyJkZXZpY2VJZCI6ImUzNGU4YTdkLTU3ZjAtNGJkYi1iMDg1LTJjN2FhZWI4ZDIzNlIiLCJ1c2VySWQiOm51bGwsIm9wdE91dCI6ZmFsc2UsInNlc3Npb25JZCI6MTcxNzEyNDUyMTkxOCwibGFzdEV2ZW50VGltZSI6MTcxNzEyNDkyMjA3MywiZXZlbnRJZCI6MjQsImlkZW50aWZ5SWQiOjAsInNlcXVlbmNlTnVtYmVyIjoyNH0=",
    },
    canonical: "https://www.gangnamunni.com/events",
    meta: {
      description:
        "국내 1위 성형정보앱 강남언니. 리얼후기부터 가격비교, 상담예약까지 한번에. 강남언니를 지금 만나보세요.",
      image: "https://www.gangnamunni.com/images/kr/meta_thumb_02.jpg",
      locale: "ko_KR",
      name: "강남언니",
      title: "이벤트 | 강남언니 - 1등 성형수술&피부시술 정보앱 | 코성형",
      twtCardType: "summary_large_image",
      type: "website",
    },
  },
  __N_SSP: true,
};
